name: Deploy to Server

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean Directory
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/housesofcards/
          rm -rf *
    
    - name: Checkout Repo
      uses: actions/checkout@v2.3.4

    - name: Transfer Repo to Directory
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/apps/housesofcards/"

    - name: Init and Run App
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/housesofcards/
          npm ci
          pm2 stop index.js
          pm2 start index.js
          echo "New commit deployed successfully"
